target 'ReactiveBeacon', :exclusive => true do
  pod "ReactiveBeacon", :path => "../"
end

target 'ReactiveBeaconTests', :exclusive => true do
  pod "ReactiveBeacon", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'OCMock', '~> 3.0.2'
  pod 'Expecta+ContainerClasses', '~> 1.0.1'
end
