workspace '../ReactiveBeacon.xcworkspace'

target 'ReactiveBeaconTests', :exclusive => true do
  pod "ReactiveBeacon", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'OCMock', '~> 3.0.2'
  pod 'Expecta+ContainerClasses', '~> 1.0.1'
end

begin
  require 'slather'
  Slather.prepare_pods(self)
rescue LoadError
  UI.warn 'Slather has been disabled (not installed).'
end
