# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - cd Example; pod update ; cd ..
script:
- xctool test -workspace Example/ReactiveBeacon.xcworkspace -scheme ReactiveBeacon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
