# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
xcode_sdk: iphonesimulator
xcode_workspace: Example/ReactiveBeacon.xcworkspace
xcode_scheme: ReactiveBeacon
before_script:
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc
  - gem i slather --no-ri --no-rdoc
  - cd Example; pod update ; cd ..
script:
- xcodebuild -workspace Example/ReactiveBeacon.xcworkspace -scheme 'iOS Tests' -sdk iphonesimulator -destination 'name=iPhone Retina (4-inch)' test | xcpretty -c | sed "s/^/ /" ; exit ${PIPESTATUS[0]}
after_success: slather
