language: objective-c
cache:
  - bundler
  - cocoapods
xcode_sdk: iphonesimulator
xcode_workspace: ReactiveBeacon.xcworkspace
xcode_scheme: ReactiveBeaconTests
before_script:
  - export LANG=en_US.UTF-8
  - gem i cocoapods -v 0.34.4 --no-ri --no-rdoc
  - gem i slather --no-ri --no-rdoc
  - cd ReactiveBeaconTests && pod install && cd $TRAVIS_BUILD_DIR
after_success: slather
