# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool test -workspace Example/ReactiveBeacon.xcworkspace -scheme ReactiveBeacon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
